# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 20:48
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
